apiVersion: apps/v1
kind: Deployment
metadata:
  name: ref-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reference
  template:
    metadata:
      labels:
        app: reference
        tier: backend
      annotations:
        author: 'John Doe'
    spec:
      containers:
        - name: app-backend
          image: googlecontainer/echoserver:1.8
          ports:
            - containerPort: 8080
